name: Deploy to Oracle Cloud Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Faz checkout do código
      - name: Checkout código
        uses: actions/checkout@v3

      # 2. Configura chave SSH para conectar no servidor Oracle Cloud
      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. Envia os arquivos do projeto para o servidor via rsync
      - name: Sincronizar arquivos com servidor
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/node/app

      # 4. Conectar no servidor e recriar containers
      - name: Deploy no Servidor Oracle Cloud
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /caminho/do/seu/projeto

            # Para containers antigos
            docker compose down || true

            # Sobe novamente
            docker compose up -d --build
          EOF